### ISSUE TITLE
eslint blocks legitimate errors in HTML context

### ISSUE THREAD

**Issue by 0sinner** [roadhump/SublimeLinter-eslint#81]
I have an .php file that is mostly HTML at this point. Inside I have tried `<script></script>` and `<script src="..."></script>`.

This resulted in an error along the lines of `Unexpected token '<'` from eslint (verified using sublimelinter debug mode).

So then I went into my project's root folder and tried to do `eslint --init`, answered all the questions and ended up with the following as my .eslintrc file.

```YAML
rules:
  indent:
    - 2
    - tab
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
env:
  browser: true
extends: 'eslint:recommended'
ecmaFeatures:
  jsx: true
  experimentalObjectRestSpread: true
plugins:
  - react
```

Opening the file again, eslint now gives me: `Error - missing semicolon. (semi)`

These errors are false positives, and block me being able to see errors from other linters. I don't plan to have much (if any) inline js code in my html/php files, so a good workaround for me would be to disable eslint in html contexts if that's possible. Of course I'd like it best if the solution made it work for all applicable contexts.

To me the error seems to be the selectors (html selector being the only one) set in `linter.py`. The selector (at least as far as I can tell) doesn't strip the `<script></script>` tags and eslint isn't expecting to start in an HTML context.

Please let me know if I can be of further assistance in troubleshooting/fixing this. Also it's entirely possible I'm just dumb and am missing some configuration flag.

EDIT: minor formatting edit and english, and clarity
